//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppReporteriayQuejas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppReportesyQuejasEntities : DbContext
    {
        public AppReportesyQuejasEntities()
            : base("name=AppReportesyQuejasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Departamento_Origen> Departamento_Origen { get; set; }
        public virtual DbSet<Departamento_Responsable> Departamento_Responsable { get; set; }
        public virtual DbSet<Estado_Clientes> Estado_Clientes { get; set; }
        public virtual DbSet<Estado_Reclamacion> Estado_Reclamacion { get; set; }
        public virtual DbSet<Oficinas> Oficinas { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Quejas> Quejas { get; set; }
        public virtual DbSet<Reclamo> Reclamo { get; set; }
        public virtual DbSet<Regiones> Regiones { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Servidor> Servidor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Quejas> Tipo_Quejas { get; set; }
        public virtual DbSet<Tipo_Reclamacion> Tipo_Reclamacion { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Zonas> Zonas { get; set; }
        public virtual DbSet<ServicioBrindado> ServicioBrindado { get; set; }
    }
}
