//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppReporteriayQuejas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calidad
    {
        public int Id_tiposervicio { get; set; }
        public string DescripcionServicio { get; set; }
        public int Id_CalidadServicio { get; set; }
        public int Id_Usuario { get; set; }
    
        public virtual TBCalidadServicio TBCalidadServicio { get; set; }
        public virtual Usuarios Usuario { get; set; }
    }
}
