//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppReporteriayQuejas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int Id_Cliente { get; set; }
        public string Identificacion { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public int Id_Estado { get; set; }
        public int Id_Oficina { get; set; }
        public int Id_Servidor { get; set; }
        public string Provincia { get; set; }
        public string Sector { get; set; }
        public string Municipio { get; set; }
        public string Barrio { get; set; }
        public string Direccion_1 { get; set; }
        public string Direccion_2 { get; set; }
        public int Id_Pais { get; set; }
    
        public virtual Estado_Clientes Estado_Clientes { get; set; }
        public virtual Oficinas Oficinas { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Servidor Servidor { get; set; }
    }
}
