//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppReporteriayQuejas
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Oficinas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oficinas()
        {
            this.Clientes = new HashSet<Clientes>();
        }
    
        public int Id_Oficina { get; set; }
        public int Id_Zonas { get; set; }
        public int Id_Region { get; set; }
        public string Descripcion { get; set; }
        public string Provincia { get; set; }
        public string Municipio { get; set; }
        public string Sector { get; set; }
        public string Barrio { get; set; }
        [Display(Name = "Direccion primaria")]
        public string Direccion_1 { get; set; }
        [Display(Name = "Direccion secundaria")]
        public string Direccion_2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual Regiones Regiones { get; set; }
        public virtual Zonas Zonas { get; set; }
    }
}
