//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppReporteriayQuejas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamo
    {
        public int Id_Reclamo { get; set; }
        public string Identificacion { get; set; }
        public int Id_Tipo_Reclamacion { get; set; }
        public string Descripcion_Reclamacion { get; set; }
        public int Id_Departamento_Origen { get; set; }
        public int Id_Departamento_Responsable { get; set; }
        public int Id_Usuario { get; set; }
        public System.DateTime Fecha_Reclamacion { get; set; }
        public System.TimeSpan Hora_Reclamacion { get; set; }
        public int Id_Estado_Reclamacion { get; set; }
        public string Comentario_Estado { get; set; }
    
        public virtual Departamento_Origen Departamento_Origen { get; set; }
        public virtual Departamento_Responsable Departamento_Responsable { get; set; }
        public virtual Tipo_Reclamacion Tipo_Reclamacion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
